# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2819b992ce0a0ae88561adfb6367d531ea93a48524ac1dca6069d051b81c796a4a6cfaf7c081e02073cced5f3782f63fd4fc517bb1df2113ac6e401ab027e52

test:
  secret_key_base: c2bda8c467014dd28397408a3fa0000bee0de310ca3cc5fbc2c3fdabcd3912d2ed691cf44a7fb244a739c8812cd0950859f5ecc341807635be59ba7faa82e37f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
